"""added location to user

Revision ID: 9e96fbacabab
Revises: 462c0c16ae77
Create Date: 2022-11-16 12:22:44.004220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e96fbacabab'
down_revision = '462c0c16ae77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'location')
    # ### end Alembic commands ###
