"""Initial migration.

Revision ID: a8f10e82a05c
Revises: 2e9a906affe2
Create Date: 2022-11-01 09:48:49.691141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f10e82a05c'
down_revision = '2e9a906affe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'title')
    # ### end Alembic commands ###
