"""upgrade new columns, latittude, longtitude

Revision ID: b2bbedbdf60e
Revises: 7b467c08680f
Create Date: 2022-12-22 13:19:36.493574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2bbedbdf60e'
down_revision = '7b467c08680f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_stat1')
    op.drop_table('sqlite_stat4')
    op.add_column('place', sa.Column('latitude', sa.Integer(), nullable=True))
    op.add_column('place', sa.Column('longitude', sa.Integer(), nullable=True))
    op.drop_column('place', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('location', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('place', 'longitude')
    op.drop_column('place', 'latitude')
    op.create_table('sqlite_stat4',
    sa.Column('tbl', sa.NullType(), nullable=True),
    sa.Column('idx', sa.NullType(), nullable=True),
    sa.Column('neq', sa.NullType(), nullable=True),
    sa.Column('nlt', sa.NullType(), nullable=True),
    sa.Column('ndlt', sa.NullType(), nullable=True),
    sa.Column('sample', sa.NullType(), nullable=True)
    )
    op.create_table('sqlite_stat1',
    sa.Column('tbl', sa.NullType(), nullable=True),
    sa.Column('idx', sa.NullType(), nullable=True),
    sa.Column('stat', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
